import MVAdaptiveAboutThisInfoSetDurationButton from './AdaptiveAboutThisInfoSetDurationButton.vue'

export { MVAdaptiveAboutThisInfoSetDurationButton }
export default MVAdaptiveAboutThisInfoSetDurationButton
